steps:
  # アプリケーション用イメージのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "docker/Dockerfile",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/forum-php-mysql:$COMMIT_SHA",
        ".",
      ]
  # Cloud SQL 接続用プロキシのイメージのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "docker/Dockerfile-proxy",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/cloud-sql-proxy:$COMMIT_SHA",
        ".",
      ]
  # アプリケーション用イメージのpush
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/forum-php-mysql:$COMMIT_SHA",
      ]
  # Cloud SQL 接続用プロキシ用イメージのpush
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/cloud-sql-proxy:$COMMIT_SHA",
      ]
  # Cloud Run へのデプロイ
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "forum-php-mysql",
        "--image",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/forum-php-mysql:$COMMIT_SHA",
        "--add-volume",
        "cloudsql-credentials,type=secret,secret=forum-seacret",
        "--add-volume-mount",
        "cloudsql-credentials,/etc/cloudsql",
        "--container",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/cloud-sql-proxy:$COMMIT_SHA",
        "--port",
        "80",
      ]
images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/forum-php-mysql:$COMMIT_SHA"
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/cloud-sql-proxy:$COMMIT_SHA"
logsBucket: "gs://forum-cloudbuild-log-cs"
options:
  logging: GCS_ONLY
substitutions:
  _REGION: "us-central1" # GCPのリージョン
  _REPO_NAME: "forum-docker" # Artifact Registry のリポジトリ名
