steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA",
        "-f",
        "Docker/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA",
      ]
images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA"
logsBucket: "gs://forum-cloudbuild-log-cs"
options:
  logging: GCS_ONLY
substitutions:
  _REGION: "us-central1" # GCPのリージョン
  _REPO_NAME: "forum-docker" # Artifact Registry のリポジトリ名
  _IMAGE_NAME: "forum-php-mysql" # ビルドするDockerイメージ名

