steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${COMMIT_SHA}",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${COMMIT_SHA}",
      ]
images:
  - "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${COMMIT_SHA}"
logsBucket: "gs://forum-cloudbuild-log-cs"
options:
  logging: GCS_ONLY
substitutions:
  REGION: "us-central1" # GCPのリージョン
  IMAGE_NAME: "forum-php-mysql" # ビルドするDockerイメージ名
