version: "3.7"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/init_data:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - ./:/var/www/html:cached
    ports:
      - 80:80
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
