FROM gcr.io/cloud-sql-proxy/cloud-sql-proxy:latest

CMD ["/cloud_sql_proxy", "-instances=forum-cloudrun-cloudsql:us-central1:forum-app-db01=tcp:3306", "-credential_file=/etc/cloudsql/credentials.json"]